[2019-01-22 20:38:33 +0000] [1246] [ERROR] Error handling request /login?userName=%E6%9E%97%E4%BA%AE&passWord=E10ADC3949BA59ABBE56E057F20F883E&passCode=qwer
Traceback (most recent call last):
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 56, in handle
    self.handle_request(listener_name, req, client, addr)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/gunicorn/workers/base_async.py", line 107, in handle_request
    respiter = self.wsgi(environ, resp.start_response)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask/app.py", line 1997, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask_socketio/__init__.py", line 43, in __call__
    start_response)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/engineio/middleware.py", line 67, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask/app.py", line 1985, in wsgi_app
    response = self.handle_exception(e)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask/app.py", line 1540, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask/app.py", line 1982, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask/app.py", line 1614, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask/app.py", line 1517, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/ubuntu/PycharmProjects/LuQiao/parking2.0/appweb/computer_web/views/user_view.py", line 24, in login
    res = set_session(params)
  File "/home/ubuntu/PycharmProjects/LuQiao/parking2.0/appweb/plugins/decorators.py", line 73, in set_session
    request.headers["Set-Cookie"] = random_cookies
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 1303, in __setitem__
    is_immutable(self)
  File "/home/ubuntu/Env/parkingPy27env/local/lib/python2.7/site-packages/werkzeug/datastructures.py", line 29, in is_immutable
    raise TypeError('%r objects are immutable' % self.__class__.__name__)
TypeError: 'EnvironHeaders' objects are immutable
[2019-01-24 10:13:15 +0000] [16549] [INFO] Starting gunicorn 19.9.0
[2019-01-24 10:13:15 +0000] [16549] [INFO] Listening at: http://0.0.0.0:8000 (16549)
[2019-01-24 10:13:15 +0000] [16549] [INFO] Using worker: sync
[2019-01-24 10:13:15 +0000] [16557] [INFO] Booting worker with pid: 16557
[2019-01-24 10:17:24 +0000] [16549] [CRITICAL] WORKER TIMEOUT (pid:16557)
[2019-01-24 10:17:24 +0000] [16557] [INFO] Worker exiting (pid: 16557)
[2019-01-24 10:17:25 +0000] [16892] [INFO] Booting worker with pid: 16892
